name: std_msgs
description: A ROS std_msgs package for dartros
version: 0.0.2
repository: https://github.com/TimWhiting/std_msgs_dart

environment:
  sdk: ">=2.7.0 < 3.0.0"

dependencies:
  buffer: ^1.0.6
  dartros: ^0.0.1
