
import 'src/msgs/Empty.dart' as Empty_msg;
export 'src/msgs/Empty.dart';
import 'src/msgs/Byte.dart' as Byte_msg;
export 'src/msgs/Byte.dart';
import 'src/msgs/Char.dart' as Char_msg;
export 'src/msgs/Char.dart';
import 'src/msgs/Int32.dart' as Int32_msg;
export 'src/msgs/Int32.dart';
import 'src/msgs/StringMessage.dart' as StringMessage_msg;
export 'src/msgs/StringMessage.dart';
import 'src/msgs/Float64.dart' as Float64_msg;
export 'src/msgs/Float64.dart';
import 'src/msgs/Duration.dart' as Duration_msg;
export 'src/msgs/Duration.dart';
import 'src/msgs/ByteMultiArray.dart' as ByteMultiArray_msg;
export 'src/msgs/ByteMultiArray.dart';
import 'src/msgs/UInt32.dart' as UInt32_msg;
export 'src/msgs/UInt32.dart';
import 'src/msgs/Int16.dart' as Int16_msg;
export 'src/msgs/Int16.dart';
import 'src/msgs/UInt8MultiArray.dart' as UInt8MultiArray_msg;
export 'src/msgs/UInt8MultiArray.dart';
import 'src/msgs/Int16MultiArray.dart' as Int16MultiArray_msg;
export 'src/msgs/Int16MultiArray.dart';
import 'src/msgs/Float32MultiArray.dart' as Float32MultiArray_msg;
export 'src/msgs/Float32MultiArray.dart';
import 'src/msgs/Time.dart' as Time_msg;
export 'src/msgs/Time.dart';
import 'src/msgs/Bool.dart' as Bool_msg;
export 'src/msgs/Bool.dart';
import 'src/msgs/Int8.dart' as Int8_msg;
export 'src/msgs/Int8.dart';
import 'src/msgs/ColorRGBA.dart' as ColorRGBA_msg;
export 'src/msgs/ColorRGBA.dart';
import 'src/msgs/Int64MultiArray.dart' as Int64MultiArray_msg;
export 'src/msgs/Int64MultiArray.dart';
import 'src/msgs/UInt64MultiArray.dart' as UInt64MultiArray_msg;
export 'src/msgs/UInt64MultiArray.dart';
import 'src/msgs/Int32MultiArray.dart' as Int32MultiArray_msg;
export 'src/msgs/Int32MultiArray.dart';
import 'src/msgs/UInt16MultiArray.dart' as UInt16MultiArray_msg;
export 'src/msgs/UInt16MultiArray.dart';
import 'src/msgs/MultiArrayLayout.dart' as MultiArrayLayout_msg;
export 'src/msgs/MultiArrayLayout.dart';
import 'src/msgs/UInt32MultiArray.dart' as UInt32MultiArray_msg;
export 'src/msgs/UInt32MultiArray.dart';
import 'src/msgs/Int64.dart' as Int64_msg;
export 'src/msgs/Int64.dart';
import 'src/msgs/Float32.dart' as Float32_msg;
export 'src/msgs/Float32.dart';
import 'src/msgs/UInt8.dart' as UInt8_msg;
export 'src/msgs/UInt8.dart';
import 'src/msgs/Int8MultiArray.dart' as Int8MultiArray_msg;
export 'src/msgs/Int8MultiArray.dart';
import 'src/msgs/MultiArrayDimension.dart' as MultiArrayDimension_msg;
export 'src/msgs/MultiArrayDimension.dart';
import 'src/msgs/UInt16.dart' as UInt16_msg;
export 'src/msgs/UInt16.dart';
import 'src/msgs/UInt64.dart' as UInt64_msg;
export 'src/msgs/UInt64.dart';
import 'src/msgs/Float64MultiArray.dart' as Float64MultiArray_msg;
export 'src/msgs/Float64MultiArray.dart';
import 'src/msgs/Header.dart' as Header_msg;
export 'src/msgs/Header.dart';

class std_msgs {
static Empty_msg.Empty Empty = Empty_msg.Empty.empty$;
static Byte_msg.Byte Byte = Byte_msg.Byte.empty$;
static Char_msg.Char Char = Char_msg.Char.empty$;
static Int32_msg.Int32 Int32 = Int32_msg.Int32.empty$;
static StringMessage_msg.StringMessage StringMessage = StringMessage_msg.StringMessage.empty$;
static Float64_msg.Float64 Float64 = Float64_msg.Float64.empty$;
static Duration_msg.Duration Duration = Duration_msg.Duration.empty$;
static ByteMultiArray_msg.ByteMultiArray ByteMultiArray = ByteMultiArray_msg.ByteMultiArray.empty$;
static UInt32_msg.UInt32 UInt32 = UInt32_msg.UInt32.empty$;
static Int16_msg.Int16 Int16 = Int16_msg.Int16.empty$;
static UInt8MultiArray_msg.UInt8MultiArray UInt8MultiArray = UInt8MultiArray_msg.UInt8MultiArray.empty$;
static Int16MultiArray_msg.Int16MultiArray Int16MultiArray = Int16MultiArray_msg.Int16MultiArray.empty$;
static Float32MultiArray_msg.Float32MultiArray Float32MultiArray = Float32MultiArray_msg.Float32MultiArray.empty$;
static Time_msg.Time Time = Time_msg.Time.empty$;
static Bool_msg.Bool Bool = Bool_msg.Bool.empty$;
static Int8_msg.Int8 Int8 = Int8_msg.Int8.empty$;
static ColorRGBA_msg.ColorRGBA ColorRGBA = ColorRGBA_msg.ColorRGBA.empty$;
static Int64MultiArray_msg.Int64MultiArray Int64MultiArray = Int64MultiArray_msg.Int64MultiArray.empty$;
static UInt64MultiArray_msg.UInt64MultiArray UInt64MultiArray = UInt64MultiArray_msg.UInt64MultiArray.empty$;
static Int32MultiArray_msg.Int32MultiArray Int32MultiArray = Int32MultiArray_msg.Int32MultiArray.empty$;
static UInt16MultiArray_msg.UInt16MultiArray UInt16MultiArray = UInt16MultiArray_msg.UInt16MultiArray.empty$;
static MultiArrayLayout_msg.MultiArrayLayout MultiArrayLayout = MultiArrayLayout_msg.MultiArrayLayout.empty$;
static UInt32MultiArray_msg.UInt32MultiArray UInt32MultiArray = UInt32MultiArray_msg.UInt32MultiArray.empty$;
static Int64_msg.Int64 Int64 = Int64_msg.Int64.empty$;
static Float32_msg.Float32 Float32 = Float32_msg.Float32.empty$;
static UInt8_msg.UInt8 UInt8 = UInt8_msg.UInt8.empty$;
static Int8MultiArray_msg.Int8MultiArray Int8MultiArray = Int8MultiArray_msg.Int8MultiArray.empty$;
static MultiArrayDimension_msg.MultiArrayDimension MultiArrayDimension = MultiArrayDimension_msg.MultiArrayDimension.empty$;
static UInt16_msg.UInt16 UInt16 = UInt16_msg.UInt16.empty$;
static UInt64_msg.UInt64 UInt64 = UInt64_msg.UInt64.empty$;
static Float64MultiArray_msg.Float64MultiArray Float64MultiArray = Float64MultiArray_msg.Float64MultiArray.empty$;
static Header_msg.Header Header = Header_msg.Header.empty$;
}
